from typing import List, Dict, Any

MIDDLE_EAST_COUNTRIES: List[Dict[str, Any]] = [
    {"code": "SA", "name": "Saudi Arabia", "name_ar": "المملكة العربية السعودية", "phone_code": "+966"},
    {"code": "AE", "name": "United Arab Emirates", "name_ar": "الإمارات العربية المتحدة", "phone_code": "+971"},
    {"code": "KW", "name": "Kuwait", "name_ar": "الكويت", "phone_code": "+965"},
    {"code": "QA", "name": "Qatar", "name_ar": "قطر", "phone_code": "+974"},
    {"code": "BH", "name": "Bahrain", "name_ar": "البحرين", "phone_code": "+973"},
    {"code": "OM", "name": "Oman", "name_ar": "عُمان", "phone_code": "+968"},
    {"code": "JO", "name": "Jordan", "name_ar": "الأردن", "phone_code": "+962"},
    {"code": "LB", "name": "Lebanon", "name_ar": "لبنان", "phone_code": "+961"},
    {"code": "EG", "name": "Egypt", "name_ar": "مصر", "phone_code": "+20"},
    {"code": "IQ", "name": "Iraq", "name_ar": "العراق", "phone_code": "+964"},
    {"code": "SY", "name": "Syria", "name_ar": "سوريا", "phone_code": "+963"},
    {"code": "PS", "name": "Palestine", "name_ar": "فلسطين", "phone_code": "+970"},
    {"code": "YE", "name": "Yemen", "name_ar": "اليمن", "phone_code": "+967"},
    {"code": "LY", "name": "Libya", "name_ar": "ليبيا", "phone_code": "+218"},
    {"code": "TN", "name": "Tunisia", "name_ar": "تونس", "phone_code": "+216"},
    {"code": "DZ", "name": "Algeria", "name_ar": "الجزائر", "phone_code": "+213"},
    {"code": "MA", "name": "Morocco", "name_ar": "المغرب", "phone_code": "+212"},
    {"code": "SD", "name": "Sudan", "name_ar": "السودان", "phone_code": "+249"},
    {"code": "MR", "name": "Mauritania", "name_ar": "موريتانيا", "phone_code": "+222"},
    {"code": "SO", "name": "Somalia", "name_ar": "الصومال", "phone_code": "+252"},
    {"code": "DJ", "name": "Djibouti", "name_ar": "جيبوتي", "phone_code": "+253"},
    {"code": "ER", "name": "Eritrea", "name_ar": "إريتريا", "phone_code": "+291"},
    {"code": "TR", "name": "Turkey", "name_ar": "تركيا", "phone_code": "+90"},
    {"code": "IR", "name": "Iran", "name_ar": "إيران", "phone_code": "+98"},
    {"code": "AF", "name": "Afghanistan", "name_ar": "أفغانستان", "phone_code": "+93"},
    {"code": "PK", "name": "Pakistan", "name_ar": "باكستان", "phone_code": "+92"},
]
